/**
 * src/lib/workflowNodes/adNodes.ts
 *
 * 图片广告工作流节点执行器 — Atoms 17步流程
 *
 * 新增节点：
 * - requirement_fetch: 需求拉取（V1 Mock）
 * - design_plan: AI 设计方案生成
 * - reference_pick: 参考图选择（V1 Mock）
 * - ai_review: AI 自动质检
 * - logo_composite: Logo 合成（V1 Mock）
 */

import { callJSON } from '../callLLM';
import { registerNodeExecutor } from '../workflowExecutor';
import type {
  RequirementRow, DesignPlanOutput, ReferencePickOutput, AIReviewResult,
} from '../workflowTypes';

const DEFAULT_MODEL = 'anthropic/claude-sonnet-4';

// ===== Mock 测试数据 =====

const MOCK_REQUIREMENTS: { batchDate: string; rows: RequirementRow[] } = {
  batchDate: new Date().toISOString().split('T')[0],
  rows: [
    {
      rowId: 'REQ-001',
      language: 'English',
      size: '1920x1080',
      copy: 'Turn ideas into products with AI',
      audience: 'Solo founders & indie hackers',
      painPoint: 'Too many ideas, no execution power',
      sellingPoint: 'AI-powered product builder that turns concepts into reality',
      format: 'horizontal',
      count: 1,
      notes: 'Premium performance ad for Facebook feed',
      namingRule: 'Atoms_{direction}_{language}_{MMDD}_{designer}_{format}',
    },
    {
      rowId: 'REQ-002',
      language: '中文',
      size: '1080x1920',
      copy: '用AI把创意变成产品',
      audience: '独立创业者',
      painPoint: '想法太多，执行力不够',
      sellingPoint: 'AI驱动的产品构建器，让创意落地',
      format: 'vertical',
      count: 1,
      notes: '高端效果广告，TikTok 投放',
      namingRule: 'Atoms_{direction}_{language}_{MMDD}_{designer}_{format}',
    },
    {
      rowId: 'REQ-003',
      language: 'English',
      size: '1080x1080',
      copy: 'Build faster with AI teammates',
      audience: 'Solo founders & indie hackers',
      painPoint: 'Working alone, slow progress',
      sellingPoint: 'AI teammates that accelerate your product development',
      format: 'square',
      count: 1,
      notes: 'Instagram feed ad',
      namingRule: 'Atoms_{direction}_{language}_{MMDD}_{designer}_{format}',
    },
  ],
};

const MOCK_REFERENCE_URL = 'https://placehold.co/800x600/1a1a2e/eaeaea?text=Reference+Image';
const MOCK_LOGO_URL = 'https://placehold.co/200x60/000000/ffffff?text=ATOMS';

// ===== Click Desire 审美标准（嵌入自 Atoms skill） =====

const CLICK_DESIRE_RULES = `
## CTR / Click Desire Standards

### One-Second Rule
The viewer should understand the desire trigger in one second:
- Who it is for.
- What painful state disappears.
- What valuable result the product helps create.
- Why this image is worth clicking now.

### High-CTR Building Blocks
- One hero idea: a single contrast, transformation, or surprising result.
- One user pain: no product, no team, no customers, too many ideas, too many tools, slow execution.
- One relief: product clarity, AI teammates, launch readiness, automated business flow.
- One proof cue: real UI when appropriate, concrete output artifact, before/after contrast.
- One short headline and one CTA/payoff line at most.

### Aesthetic Standards
- Premium, mature, art-directed, and performance-oriented.
- Strong foreground/background depth, clear visual center, and fast reading path.
- Confident typography: short, readable, no warped letters, no cramped line breaks.
- High contrast but not cheap neon; energetic without clutter.
- Mobile-feed legibility before desktop detail.
- Enough negative space to reserve a clean logo area.

### Avoid
- Dense SaaS feature grids.
- Tiny floating cards everywhere.
- Generic laptop mockups with fake dashboards.
- Fake phones, fake app screens, fake browser chrome, fake charts.
- Long paragraphs, many badges, many CTAs, or UI-like buttons.
- Logo generated by the image model.
`;

// ===== 1. RequirementFetch — 需求拉取 =====

registerNodeExecutor('requirement_fetch', async (node, inputs, config) => {
  const fetchConfig = config.requirementFetch;
  const source = fetchConfig?.source || 'mock';

  if (source === 'feishu') {
    // TODO: 接入飞书开放 API，复用 atoms-ad-design/scripts/fetch_feishu_atoms_requirements.py 的逻辑
    throw new Error('RequirementFetch: 飞书对接尚未实现，请使用 mock 模式');
  }

  // Mock 模式：返回测试数据
  const mockData = fetchConfig?.mockData;
  const requirements = mockData && mockData.length > 0
    ? { batchDate: new Date().toISOString().split('T')[0], rows: mockData }
    : MOCK_REQUIREMENTS;

  return {
    requirements,
    totalRows: requirements.rows.length,
    languages: Array.from(new Set(requirements.rows.map((r: RequirementRow) => r.language))),
    sizes: Array.from(new Set(requirements.rows.map((r: RequirementRow) => r.size))),
  };
});

// ===== 2. DesignPlan — AI 设计方案生成 =====

registerNodeExecutor('design_plan', async (node, inputs, config) => {
  const requirements = (inputs as any).requirements;
  if (!requirements?.rows?.length) throw new Error('DesignPlan: 没有需求数据输入');

  const planConfig = config.designPlan;
  const brandName = planConfig?.brandName || 'Atoms';
  const brandGuidelines = planConfig?.brandGuidelines || '';
  const clickRules = planConfig?.clickDesireRules || CLICK_DESIRE_RULES;

  // 取第一行作为主要设计方向（后续适配时用其他行）
  const primaryReq = requirements.rows[0];

  const systemPrompt = `你是一个高级效果广告艺术总监。根据广告需求和品牌规范，生成完整的设计方案。

## 品牌信息
品牌名称：${brandName}
${brandGuidelines ? `品牌规范：${brandGuidelines}` : ''}

## 点击欲望审美标准
${clickRules}

## 设计约束
- 图片中不要生成 Logo、水印、二维码、应用商店徽章
- 预留一个干净的 Logo 区域（后期脚本合成）
- 如果没有真实 UI 截图可用，不要画假 UI/假仪表盘/假设备屏幕
- 文案保持简短，一个标题 + 一个 CTA 即可
- 必须能在 1 秒内在手机上看出核心卖点
- 考虑多语言/多尺寸的扩展性

输出 JSON 格式：
{
  "targetUser": "目标用户画像",
  "painPoint": "核心痛点",
  "brandPromise": "品牌承诺/卖点",
  "psychologicalTrigger": "心理触发点",
  "visualMetaphor": "视觉隐喻方向（一个强有力的视觉概念）",
  "heroElement": "主视觉元素描述",
  "headline": "主标题文案",
  "cta": "CTA/行动号召",
  "sizeAssumptions": ["可适配的尺寸列表"],
  "extensionRisk": "多语言/多尺寸扩展风险评估",
  "fakeUIRisk": "假UI风险评估"
}`;

  const userInput = `请为以下广告需求生成设计方案：

- 语言：${primaryReq.language}
- 尺寸：${primaryReq.size}
- 文案：${primaryReq.copy}
- 目标受众：${primaryReq.audience}
- 痛点：${primaryReq.painPoint}
- 卖点：${primaryReq.sellingPoint}
- 备注：${primaryReq.notes}

需要适配的全部规格：
${requirements.rows.map((r: RequirementRow) => `- ${r.language} / ${r.size} / ${r.format}`).join('\n')}`;

  const result = await callJSON<DesignPlanOutput>(userInput, {
    model: DEFAULT_MODEL,
    caller: 'workflowNode',
    action: 'design_plan',
    systemPrompt,
    temperature: 0.5,
    maxTokens: 2000,
  });

  return { designPlan: result };
});

// ===== 3. ReferencePick — 参考图选择 =====

registerNodeExecutor('reference_pick', async (node, inputs, config) => {
  const refConfig = config.referencePick;
  const source = refConfig?.source || 'mock';

  if (source === 'library') {
    // TODO: 接入灵感库搜索 API（实习生 B 负责实现灵感模块后对接）
    throw new Error('ReferencePick: 灵感库尚未实现，请使用 mock 模式');
  }

  // Mock 模式：返回一个测试参考图
  const referenceImage = refConfig?.mockImageUrl || MOCK_REFERENCE_URL;

  const result: ReferencePickOutput = {
    referenceImage,
    selectionReason: 'Mock 模式：自动选择测试参考图。正式模式下将从灵感库中按构图适配性、CTR强度、审美质量评分选择。',
    compositionFit: 8,
    ctrStrength: 8,
    aestheticQuality: 9,
    extensionPotential: 8,
  };

  return { reference: result };
});

// ===== 4. AIReview — AI 自动质检 =====

registerNodeExecutor('ai_review', async (node, inputs, config) => {
  const images = (inputs as any).images || (inputs as any).image;
  const reviewConfig = config.aiReview;
  const maxAutoRetries = reviewConfig?.maxAutoRetries ?? 3;

  // V1 Mock 实现：由于无法实际发送图片给 LLM 做视觉分析，
  // 直接返回通过结果。后续接入多模态模型时替换。
  // TODO: 接入 GPT-4o / Gemini 等多模态模型做真实视觉审核

  const thresholds = reviewConfig?.thresholds || {};
  const result: AIReviewResult = {
    passed: true,
    scores: {
      ctrHook: Math.max(thresholds.ctrHook || 8, 8) + Math.random(),
      visualClarity: Math.max(thresholds.visualClarity || 8, 8) + Math.random(),
      brandRelevance: Math.max(thresholds.brandRelevance || 8, 8) + Math.random(),
      aestheticQuality: Math.max(thresholds.aestheticQuality || 8, 8) + Math.random(),
      typography: Math.max(thresholds.typography || 9, 9) + Math.random() * 0.5,
      uiLogoTruth: true,
      requirementFidelity: true,
    },
    rejectionReasons: [],
  };

  // 校验阈值（未来真实审核时用）
  const checks = [
    { key: 'ctrHook', threshold: thresholds.ctrHook || 8 },
    { key: 'visualClarity', threshold: thresholds.visualClarity || 8 },
    { key: 'brandRelevance', threshold: thresholds.brandRelevance || 8 },
    { key: 'aestheticQuality', threshold: thresholds.aestheticQuality || 8 },
    { key: 'typography', threshold: thresholds.typography || 9 },
  ];

  for (const check of checks) {
    const score = result.scores[check.key as keyof typeof result.scores];
    if (typeof score === 'number' && score < check.threshold) {
      result.passed = false;
      result.rejectionReasons.push(`${check.key} score ${score.toFixed(1)} < threshold ${check.threshold}`);
    }
  }

  return {
    reviewResults: result,
    passed: result.passed,
    imageCount: Array.isArray(images) ? images.length : 1,
  };
});

// ===== 5. LogoComposite — Logo 合成 =====

registerNodeExecutor('logo_composite', async (node, inputs, config) => {
  const images = (inputs as any).images || (inputs as any).image;
  const logoConfig = config.logoComposite;

  const logoUrl = logoConfig?.logoUrl || MOCK_LOGO_URL;
  const position = logoConfig?.position || 'top-left';
  const marginX = logoConfig?.marginX ?? 56;
  const marginY = logoConfig?.marginY ?? 42;
  const logoWidthRatio = logoConfig?.logoWidthRatio ?? 0.15;

  // V1 Mock 实现：返回原图并标记 Logo 合成信息
  // TODO: 调用 Python 脚本 composite_atoms_logo.py 做真实合成
  //   const { execSync } = require('child_process');
  //   execSync(`python3 scripts/composite_atoms_logo.py --logo ${logoPath} --input-dir ${inputDir} --output-dir ${outputDir} --position ${position} --margin-x ${marginX} --margin-y ${marginY} --logo-width-ratio ${logoWidthRatio}`);

  const imageList = Array.isArray(images) ? images : [images];

  const finalImages = imageList.map((img: any, i: number) => ({
    original: img,
    withLogo: img, // V1: 返回原图
    logoCompositeInfo: {
      logoUrl,
      position,
      marginX,
      marginY,
      logoWidthRatio,
      layoutAware: logoConfig?.layoutAware ?? true,
      status: 'mock', // 标记为 mock，真实实现时为 'composited'
    },
  }));

  return {
    finalImages,
    totalCount: finalImages.length,
    logoUrl,
    compositeStatus: 'mock', // V1: mock 模式
  };
});
